import { TourStep } from '../types/tour';

export const tourSteps: TourStep[] = [
  {
    id: 'welcome',
    target: '[data-tour="app-container"]',
    title: '👋 Welcome to Lottie Inspector!',
    content: 'A powerful tool for inspecting, analyzing, and editing Lottie animations. Let\'s take a quick tour to get you started!',
    placement: 'center',
  },
  {
    id: 'upload',
    target: '[data-tour="upload-button"]',
    title: '📤 Upload Animations',
    content: 'Start by clicking here to upload a Lottie JSON file from your computer. You can inspect any Lottie animation!',
    placement: 'bottom',
  },
  {
    id: 'layers-panel',
    target: '[data-tour="left-panel"]',
    title: '📋 Layers Browser',
    content: 'This panel shows all layers in your animation. You can expand groups, toggle visibility, and select layers to inspect their properties.',
    placement: 'right',
  },
  {
    id: 'layer-selection',
    target: '[data-tour="layer-item"]',
    title: '🎯 Select a Layer',
    content: 'Click any layer to select it. The eye icon toggles visibility, and the lock icon prevents editing. Layer colors indicate their type.',
    placement: 'right',
  },
  {
    id: 'center-panel',
    target: '[data-tour="center-panel"]',
    title: '🎬 Animation Preview',
    content: 'Watch your animation play in real-time here. All changes you make will be reflected instantly in this preview area.',
    placement: 'left',
  },
  {
    id: 'properties-panel',
    target: '[data-tour="right-panel"]',
    title: '⚙️ Properties Inspector',
    content: 'Selected layer properties appear here. View and edit position, rotation, scale, opacity, colors, and more!',
    placement: 'left',
  },
  {
    id: 'timeline',
    target: '[data-tour="bottom-timeline"]',
    title: '⏱️ Timeline & Keyframes',
    content: 'Control playback, scrub through frames, and see keyframe markers. Perfect for frame-by-frame analysis!',
    placement: 'top',
  },
  {
    id: 'ai-chat-tab',
    target: '[data-tour="ai-chat-tab"]',
    title: '🤖 AI Chat Assistant',
    content: 'NEW! Switch to this tab to edit animations using natural language. Just describe what you want, and AI will generate the changes!',
    placement: 'right',
  },
  {
    id: 'ai-commands',
    target: '[data-tour="ai-chat-tab"]',
    title: '✨ Natural Language Editing',
    content: 'Try commands like "Make it bounce", "Rotate 360 degrees", or "Move 50 pixels right". The AI understands animation concepts!',
    placement: 'right',
  },
  {
    id: 'render-mode',
    target: '[data-tour="render-mode"]',
    title: '🎨 Render Mode',
    content: 'Toggle between SVG (crisp vectors) and Canvas (better performance for complex animations) rendering modes.',
    placement: 'bottom',
  },
  {
    id: 'theme',
    target: '[data-tour="theme-toggle"]',
    title: '🌓 Theme Toggle',
    content: 'Switch between light and dark themes. Dark mode is easier on your eyes during long editing sessions!',
    placement: 'bottom',
  },
  {
    id: 'export',
    target: '[data-tour="export-button"]',
    title: '💾 Export Your Work',
    content: 'When you\'re done editing, click here to download your modified Lottie animation as a JSON file.',
    placement: 'bottom',
  },
  {
    id: 'complete',
    target: '[data-tour="app-container"]',
    title: '🎉 You\'re All Set!',
    content: 'You now know the basics of Lottie Inspector. Upload an animation and start exploring. Happy animating!',
    placement: 'center',
  },
];
